package com.sporttourism.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Data;
import lombok.With;
import lombok.experimental.FieldDefaults;

@DynamoDBTable(tableName = "comment")
@Data
@Builder
@With
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Comment {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey
  String id;

  @DynamoDBAttribute
  String commentText;

  @DynamoDBAttribute
  String authorUsername;

  @DynamoDBAttribute
  Long date;
}
