package com.sporttourism.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.Set;
import javax.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Data;
import lombok.With;
import lombok.experimental.FieldDefaults;

@DynamoDBTable(tableName = "sportTrip")
@Data
@Builder
@With
@FieldDefaults(level = AccessLevel.PRIVATE)
public class SportTrip {

//  @Id
//  SportTripId sportTripId;

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey
  String id;

  @DynamoDBAttribute
  @NotNull
  String locationName;

  @DynamoDBAttribute
  String tripDescription;

  @DynamoDBAttribute
  @NotNull
  String tripDate;

  @DynamoDBAttribute
  @NotNull
  String tripDifficulty;

  //  @DynamoDBRangeKey
  @DynamoDBAttribute
  @NotNull
  String tripType;

  @DynamoDBAttribute
  @NotNull
  Integer tripDuration;

  @DynamoDBAttribute
  Set<User> participants;

  @DynamoDBAttribute
  Integer maxGroupCount;
  @DynamoDBAttribute
  Double cost;

  Set<Comment> comments;

  @DynamoDBAttribute
  Boolean isFinished;
  @DynamoDBAttribute
  Boolean isRemoved;
}
