package com.sporttourism.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.sporttourism.utils.CommentConverter;
import java.util.List;
import javax.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.With;
import lombok.experimental.FieldDefaults;

@DynamoDBTable(tableName = "sportTrip")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@With
@FieldDefaults(level = AccessLevel.PRIVATE)
public class SportTrip {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey
  String id;

  @DynamoDBAttribute
  String tripGuideId;

  @DynamoDBAttribute
  @NotNull
  String locationName;

  @DynamoDBAttribute
  String tripDescription;

  @DynamoDBAttribute
  @NotNull
  String tripDate;

  @DynamoDBAttribute
  @NotNull
  String tripDifficulty;

  @DynamoDBAttribute
  @NotNull
  String tripType;

  @DynamoDBAttribute
  @NotNull
  Integer tripDuration;

//  @DynamoDBAttribute
//  List<String> participants;

  @DynamoDBAttribute
  Integer maxGroupCount;
  @DynamoDBAttribute
  Double cost;

  @DynamoDBAttribute
  @CommentConverter
  List<Comment> comments;

  @DynamoDBAttribute
  Boolean isCompleted;
}
