package com.sporttourism.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import javax.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.With;
import lombok.experimental.FieldDefaults;

@DynamoDBTable(tableName = "sportTrip")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@With
@EqualsAndHashCode/*(callSuper = true)*/
@ToString
@FieldDefaults(level = AccessLevel.PRIVATE)
public class SportTrip/* extends BaseEntity*/ {

//  @Id
//  SportTripId sportTripId;

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "sportTripId")
  String id;

  @DynamoDBAttribute
  @NotNull
  String locationName;

  @DynamoDBAttribute
  String description;

  @DynamoDBAttribute
  @NotNull
  String tripDate;

  @DynamoDBAttribute
  @NotNull
  String tripDifficulty;

  //  @DynamoDBRangeKey
  @DynamoDBAttribute
  @NotNull
  String tripType;

  @DynamoDBAttribute
  @NotNull
  Integer tripDuration;

//  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sportTrip")
//  Set<User> participants;

  @DynamoDBAttribute
  Integer maxGroupCount;
  @DynamoDBAttribute
  Double cost;

//  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sportTrip")
//  Set<Comment> comments;

  @DynamoDBAttribute
  Boolean isFinished;
  @DynamoDBAttribute
  Boolean isRemoved;
}
