package com.sporttourism.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import javax.validation.constraints.Email;
import javax.validation.constraints.Size;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Data;
import lombok.NonNull;
import lombok.With;
import lombok.experimental.FieldDefaults;

@DynamoDBTable(tableName = "user")
@Data
@Builder
@With
@FieldDefaults(level = AccessLevel.PRIVATE)
public class User {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey
  String id;

  @DynamoDBAttribute
  @NonNull
  @Size(max = 40)
  String userName;

  @DynamoDBAttribute
  @Size(max = 20)
  String phone;

  @DynamoDBAttribute
  @Size(max = 40)
  @Email
  String email;

}
